#ifndef _ALTERA_ARM_A9_HPS_H_
#define _ALTERA_ARM_A9_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'Computer_System' in
 * file 'Computer_System.sopcinfo'.
 */

/*
 * This file contains macros for module 'ARM_A9_HPS' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'NPU_TOP_0_avs_reset', class 'NPU_TOP'
 * The macros are prefixed with 'NPU_TOP_0_AVS_RESET_'.
 * The prefix is the slave descriptor.
 */
#define NPU_TOP_0_AVS_RESET_COMPONENT_TYPE NPU_TOP
#define NPU_TOP_0_AVS_RESET_COMPONENT_NAME NPU_TOP_0
#define NPU_TOP_0_AVS_RESET_BASE 0x0
#define NPU_TOP_0_AVS_RESET_SPAN 4
#define NPU_TOP_0_AVS_RESET_END 0x3

/*
 * Macros for device 'NPU_TOP_0_avs_write', class 'NPU_TOP'
 * The macros are prefixed with 'NPU_TOP_0_AVS_WRITE_'.
 * The prefix is the slave descriptor.
 */
#define NPU_TOP_0_AVS_WRITE_COMPONENT_TYPE NPU_TOP
#define NPU_TOP_0_AVS_WRITE_COMPONENT_NAME NPU_TOP_0
#define NPU_TOP_0_AVS_WRITE_BASE 0x4
#define NPU_TOP_0_AVS_WRITE_SPAN 4
#define NPU_TOP_0_AVS_WRITE_END 0x7

/*
 * Macros for device 'NPU_TOP_0_avs_read', class 'NPU_TOP'
 * The macros are prefixed with 'NPU_TOP_0_AVS_READ_'.
 * The prefix is the slave descriptor.
 */
#define NPU_TOP_0_AVS_READ_COMPONENT_TYPE NPU_TOP
#define NPU_TOP_0_AVS_READ_COMPONENT_NAME NPU_TOP_0
#define NPU_TOP_0_AVS_READ_BASE 0x8
#define NPU_TOP_0_AVS_READ_SPAN 1
#define NPU_TOP_0_AVS_READ_END 0x8

/*
 * Macros for device 'NPU_TOP_0_avs_write_instr', class 'NPU_TOP'
 * The macros are prefixed with 'NPU_TOP_0_AVS_WRITE_INSTR_'.
 * The prefix is the slave descriptor.
 */
#define NPU_TOP_0_AVS_WRITE_INSTR_COMPONENT_TYPE NPU_TOP
#define NPU_TOP_0_AVS_WRITE_INSTR_COMPONENT_NAME NPU_TOP_0
#define NPU_TOP_0_AVS_WRITE_INSTR_BASE 0x10
#define NPU_TOP_0_AVS_WRITE_INSTR_SPAN 4
#define NPU_TOP_0_AVS_WRITE_INSTR_END 0x13


#endif /* _ALTERA_ARM_A9_HPS_H_ */
